name: Deploy static HTML from Java to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile and run Java app
        working-directory: ./app
        run: |
          mvn compile
          mvn exec:java -Dexec.mainClass="com.registro.Main"

      - name: Run static analysis and copy reports
        working-directory: ./app
        run: |
          mvn checkstyle:checkstyle
          mvn jacoco:report
          mvn pmd:check
          mkdir -p output
          cp -r target/site/* output/

      - name: Generate custom index.html
        working-directory: ./app
        run: |
          cat <<EOF > output/index.html
          <!DOCTYPE html>
          <html lang="es">
          <head>
            <meta charset="UTF-8">
            <title>Reporte de Análisis Estático</title>
            <style>
              body { font-family: sans-serif; padding: 2rem; background-color: #f9f9f9; }
              h1 { color: #333; }
              ul { list-style: none; padding: 0; }
              li { margin: 1rem 0; }
              a { text-decoration: none; color: #0366d6; font-weight: bold; }
            </style>
          </head>
          <body>
            <h1>📊 Reportes de Análisis Estático</h1>
            <ul>
              <li><a href="checkstyle.html">🔍 Checkstyle Report</a></li>
              <li><a href="pmd.html">🛠️ PMD Report</a></li>
              <li><a href="jacoco/index.html">📈 Cobertura de Código (Jacoco)</a></li>
            </ul>
          </body>
          </html>
EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: app/output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4